BEGIN;

SELECT plan(3);

--------------------------------------------------------------------------------

DELETE FROM app.vtubers;

-- Relaxes the restriction of setting IDs.
ALTER TABLE app.vtubers
  ALTER vtuber_id SET GENERATED BY DEFAULT;

INSERT
  INTO app.vtubers(vtuber_id, name, description, origin)
  VALUES (1 :: BIGINT, 'Veibae', 'A succubus', 'vshojo');

SELECT row_eq(
  $$ SELECT vtuber_id, smashes, passes FROM app.vtubers $$,
  row(1 :: BIGINT, 0 :: BIGINT, 0 :: BIGINT)
);


-- smash action
SELECT row_eq(
  $$ SELECT vtuber_id, smashes, passes FROM app.vote(1 :: BIGINT, 'smashed' :: app.ACTION) $$,
  row(1 :: BIGINT, 1 :: BIGINT, 0 :: BIGINT)
);

-- pass action
SELECT row_eq(
  $$
    SELECT vtuber_id, smashes, passes
      FROM app.vote(1 :: BIGINT, 'passed' :: app.ACTION)
  $$,
  row(1 :: BIGINT, 1 :: BIGINT, 1 :: BIGINT)
);


--------------------------------------------------------------------------------

SELECT * FROM finish();

ROLLBACK;
